[build]
  command = "./build.js"
  publish = "build/"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [plugins.inputs.thresholds]
    performance = 1
    accessibility = 1
    best-practices = 1
    seo = 0.95
